# Consider the below code to answer further questions:


In [5]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)


## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.


Yes, there is a difference in the data types of variables list_ and array_list. The variable list_ is a Python list, and array_list is a NumPy array.

You can print the data types of both variables using the type function. Here's the code

In [6]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print the data types
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


Here, <class 'list'> indicates the data type of the list_ variable is a Python list, and <class 'numpy.ndarray'> indicates the data type of the array_list variable is a NumPy array.

# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print the data type of each element in the list
print("Data type of each element in list_:")
for element in list_:
    print(type(element))

# Print the data type of each element in the NumPy array
print("\nData type of each element in array_list:")
for element in array_list:
    print(type(element))


Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [2]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)


In [3]:
array_list = np.array(object=list_, dtype=int)


In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print the data type of each element in the list
print("Data type of each element in list_:")
for element in list_:
    print(type(element))

# Print the data type of each element in the NumPy array (after dtype=int)
print("\nData type of each element in array_list:")
for element in array_list:
    print(type(element))


Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


# Consider the below code to answer further questions:
- import numpy as np
- num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
- num_array = np.array(object = num_list)

# Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [5]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find characteristics of num_array
shape_of_array = num_array.shape
size_of_array = num_array.size

# Print the results
print("Shape of num_array:", shape_of_array)
print("Size of num_array:", size_of_array)


Shape of num_array: (2, 3)
Size of num_array: 6


# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).

In [6]:
import numpy as np

# Create a numpy array of zeros with shape (3, 3)
zero_matrix = np.zeros((3, 3))

# Print the zero matrix
print("3x3 Matrix of Zeros:")
print(zero_matrix)


3x3 Matrix of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [7]:
import numpy as np

# Create an identity matrix of shape (5, 5)
identity_matrix = np.eye(5)

# Print the identity matrix
print("Identity Matrix of Shape (5, 5):")
print(identity_matrix)


Identity Matrix of Shape (5, 5):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
